image: Ubuntu1804  # образ для сборки

stack: node 12  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - yarn  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn lint && yarn test  # скрипт тестирования

environment:
  access_token:
    secure: 3aecce279e9b5c3d8dea95dbfbdb2d52c9316813

deploy_script: # скрипт развёртывания
- git config --global credential.helper store
- git config --global user.name "Alexey Shishkin"
- git config --global user.email %github_email%
- echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
- npx push-dir --dir=dist --branch=gh-pages --force --verbose
